{"uuid": "a5cec5d0-aa06-4b49-8188-89c845967431", "children": ["0ac151aa-4699-4d27-8cb5-4fef5d699836"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_INTERNET_DISCONNECTED\n  (Session info: chrome=91.0.4472.77)\n\n", "trace": "  File \"d:\\pythonproject\\livepuresmart\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\pythonproject\\livepuresmart\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\pythonproject\\livepuresmart\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\pythonProject\\livePureSmart\\testcases\\conftest.py\", line 17, in setup\n    driver.get(url)\n  File \"d:\\pythonproject\\livepuresmart\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"d:\\pythonproject\\livepuresmart\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\pythonproject\\livepuresmart\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1625048124840, "stop": 1625048128174}], "start": 1625048124840, "stop": 1625048128247}