{"uuid": "0be0dec9-774c-40d3-9473-f3193f2c3a77", "children": ["90accaaa-cc25-4e02-9d8d-d1db6d1c886a"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_INTERNET_DISCONNECTED\n  (Session info: chrome=91.0.4472.77)\n\n", "trace": "  File \"d:\\pythonproject\\livepuresmart\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\pythonproject\\livepuresmart\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\pythonproject\\livepuresmart\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\pythonProject\\livePureSmart\\testcases\\conftest.py\", line 17, in setup\n    driver.get(url)\n  File \"d:\\pythonproject\\livepuresmart\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"d:\\pythonproject\\livepuresmart\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\pythonproject\\livepuresmart\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1625048141998, "stop": 1625048144898}], "start": 1625048141998, "stop": 1625048144968}